from pathlib import Path

path = Path('analysis_engine.js')
text = path.read_text(encoding='utf-8')

old = '''  function renderFixture(f) {\n    const title = `${f.opponent} ${f.home ? 'Home' : 'Away'} · FDR ${f.difficulty} · historical ${Number(f.historical_ppg ?? 0).toFixed(1)} pts/match · ${f.historical_matches || 0} meeting${f.historical_matches === 1 ? '' : 's'}`;\n    return `<span class="analysis-fixture ${fixtureClass(Number(f.difficulty))}" title="${escapeHtml(title)}"><b>GW${f.gw}</b><span>${escapeHtml(f.opponent)}</span><strong>${f.home ? 'H' : 'A'}</strong><small>${Number(f.historical_ppg ?? 0).toFixed(1)}</small></span>`;\n  }'''

new = '''  function renderFixture(f) {\n    const meetings = Number(f.historical_matches || 0);\n    const venueMeetings = Number(f.venue_matches || 0);\n    const adjusted = Number(f.historical_ppg ?? 0);\n    const venuePpg = Number(f.historical_venue_ppg ?? 0);\n    const title = `${f.opponent} ${f.home ? 'Home' : 'Away'} · FDR ${f.difficulty} · ${adjusted.toFixed(1)} pts/match`;\n    return `<details class="analysis-fixture ${fixtureClass(Number(f.difficulty))}" title="${escapeHtml(title)}">\n      <summary><b>GW${f.gw}</b><span>${escapeHtml(f.opponent)}</span><strong>${f.home ? 'H' : 'A'}</strong><small>${adjusted.toFixed(1)}</small></summary>\n      <div class="analysis-history-detail">\n        <div><b>Historical return</b><strong>${adjusted.toFixed(1)} pts/match</strong></div>\n        <div><b>${f.home ? 'Home' : 'Away'} return</b><strong>${venueMeetings ? venuePpg.toFixed(1) : '—'} pts/match</strong></div>\n        <div><b>Meetings</b><strong>${meetings}</strong></div>\n        <div><b>Venue meetings</b><strong>${venueMeetings}</strong></div>\n        <span>Adjusted for small samples; the venue record is shrunk toward the player's broader record vs this opponent.</span>\n      </div>\n    </details>`;\n  }'''

if old not in text:
    raise SystemExit('renderFixture block not found; refusing to patch')
text = text.replace(old, new, 1)

needle = '''      .analysis-fixtures{display:flex;gap:5px;min-width:330px;overflow:hidden}.analysis-fixture{display:grid;grid-template-columns:auto 1fr auto;grid-template-rows:auto auto;align-items:center;column-gap:4px;min-width:62px;max-width:70px;padding:5px 6px;border-radius:6px;font-size:8px;line-height:1.15;border:1px solid transparent;flex:0 0 62px}.analysis-fixture span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.analysis-fixture small{grid-column:1/-1;margin-top:2px;font-size:8px;font-weight:800}.analysis-fixture.easy{border-color:#bbf7d0}.analysis-fixture.medium{border-color:#fde68a}.analysis-fixture.hard{border-color:#fecaca}.analysis-mini{font-size:8px;color:#94a3b8;margin-top:2px}.reasons{max-width:245px;gap:3px}.reasons span{font-size:8px}'''

replacement = '''      .analysis-fixtures{display:flex;gap:5px;min-width:330px;overflow:visible;align-items:flex-start}.analysis-fixture{position:relative;display:block;min-width:62px;max-width:70px;padding:0;border-radius:6px;font-size:8px;line-height:1.15;border:1px solid transparent;flex:0 0 62px;background:#fff;z-index:1}.analysis-fixture[open]{z-index:20;min-width:190px;max-width:220px}.analysis-fixture summary{display:grid;grid-template-columns:auto 1fr auto;grid-template-rows:auto auto;align-items:center;column-gap:4px;padding:5px 6px;cursor:pointer;list-style:none}.analysis-fixture summary::-webkit-details-marker{display:none}.analysis-fixture summary span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.analysis-fixture summary small{grid-column:1/-1;margin-top:2px;font-size:8px;font-weight:800}.analysis-fixture.easy{border-color:#bbf7d0}.analysis-fixture.medium{border-color:#fde68a}.analysis-fixture.hard{border-color:#fecaca}.analysis-history-detail{position:absolute;top:100%;left:0;width:210px;margin-top:4px;padding:8px;background:#fff;border:1px solid var(--line);border-radius:8px;box-shadow:0 8px 24px rgba(15,23,42,.14);display:grid;grid-template-columns:1fr 1fr;gap:6px;font-size:8px}.analysis-history-detail div{background:#f8fafc;border-radius:5px;padding:5px}.analysis-history-detail b{display:block;color:#64748b;font-size:7px;text-transform:uppercase;letter-spacing:.03em}.analysis-history-detail strong{display:block;margin-top:2px;font-size:9px}.analysis-history-detail>span{grid-column:1/-1;color:#64748b;line-height:1.35}.analysis-mini{font-size:8px;color:#94a3b8;margin-top:2px}.reasons{max-width:245px;gap:3px}.reasons span{font-size:8px}'''

if needle not in text:
    raise SystemExit('analysis fixture CSS block not found; refusing to patch')
text = text.replace(needle, replacement, 1)
path.write_text(text, encoding='utf-8')
print('patched historical fixture accordion UI')
